---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "adaptai-chart.secret.name" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
type: Opaque
data:
  OPENROUTER_API_KEY: {{ required "An OpenRouter API key is required!" .Values.secret.OPENROUTER_API_KEY | b64enc }}