# Default values for adaptai-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "adaptai"
fullnameOverride: ""
namespaceOverride: "adaptai"

# Deployment configuration
deployment:
  replicaCount: 1
  port: 5500
  image:
    repository: florienb/adaptai
    pullPolicy: Always
    tag: latest
  podLabels: {}
  securityContext:
    capabilities:
      drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"
  livenessProbe:
    httpGet:
      path: /healthcheck
      port: http
      initialDelaySeconds: 10
      periodSeconds: 20
  readinessProbe:
    httpGet:
     path: /healthcheck
     port: http
     initialDelaySeconds: 5
     periodSeconds: 10
  nodeSelector: {}
  tolerations: []
  affinity: {}
  podAnnotations: {}
  podSecurityContext: {}

# AI Model to use
AImodel: "meta-llama/llama-4-scout:free"
# Log level
# logLevel: "DEBUG"

# Secret configuration
secret:
  OPENROUTER_API_KEY: "test"

# Service configuration
service:
  type: NodePort
  port: 80
  targetPort: 5500

# Horizontal Pod Autoscaler configuration
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
