name: CI/CD pipeline for app
on:
    push:
        branches:
            - main

jobs:
    test-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5
            - name: Set up Python 3.9
              uses: actions/setup-python@v5
              with:
                python-version: 3.9
            - name: Double-checking python version
              run: python -c "import sys; print(sys.version)"
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Run tests
              run: |
                python tests/test.py
            - name: Setup Docker buildx
              if: success()
              uses: docker/setup-buildx-action@v3
            - name: Login to DockerHub
              if: success()
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }} 
            - name: Extract Docker image metadata
              if: success()
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ secrets.DOCKER_USERNAME }}/adaptai
                tags: |
                    type=ref,event=branch
                    type=sha
                    type=raw,value=latest,enable={{is_default_branch}}
            - name: Build and push Docker image
              if: success()
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
            - name: Success message
              if: success()
              run: |
                echo "All steps completed successfully!"
                echo "Docker image pushed to DockerHub."
                echo "Image tags: ${{ steps.meta.outputs.tags }}"